from typing import Iterable, Protocol

from app.domain.host import Host


class HostRepository(Protocol):
    def create(self, host: Host) -> Host: ...
    def get(self, workspace_id: str, host_id: str) -> Host | None: ...
    def find_by_token_hash(self, token_hash: str) -> Host | None: ...
    def list_by_workspace(self, workspace_id: str) -> Iterable[Host]: ...
    def update(self, host: Host) -> Host: ...
    def delete(self, host: Host) -> None: ...
