from typing import Iterable, Protocol

from app.domain.job import Job


class JobRepository(Protocol):
    def create(self, job: Job) -> Job: ...
    def get(self, job_id: str) -> Job | None: ...
    def list_by_host(self, workspace_id: str, host_id: str) -> Iterable[Job]: ...
    def list_by_workspace(self, workspace_id: str) -> Iterable[Job]: ...
    def update(self, job: Job) -> Job: ...
    def delete(self, job: Job) -> None: ...
