from typing import Protocol

from app.domain.workspace import Workspace


class WorkspaceRepository(Protocol):
    def create(self, workspace: Workspace) -> Workspace: ...
    def get(self, workspace_id: str) -> Workspace | None: ...
    def update(self, workspace: Workspace) -> Workspace: ...
    def delete(self, workspace: Workspace) -> None: ...
