version: 2

project_name: obsern

before:
  hooks:
    - go -C cli mod tidy

builds:
  - id: cli
    dir: ./cli
    ldflags:
      - -s -w -X github.com/kazuki-kanaya/obsern/cli/cmd.version={{.Version}}
    main: .
    binary: obsern
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - formats: [tar.gz]
    files:
      - src: cli/LICENSE
        dst: LICENSE
      - src: cli/THIRD_PARTY_NOTICES.md
        dst: THIRD_PARTY_NOTICES.md
      - src: cli/licenses/APACHE-2.0.txt
        dst: licenses/APACHE-2.0.txt
      - src: cli/licenses/BSD-3-Clause.txt
        dst: licenses/BSD-3-Clause.txt
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt
