version: "3"

includes:
  api:
    taskfile: ./api/Taskfile.yaml
    dir: ./api
  cli:
    taskfile: ./cli/Taskfile.yaml
    dir: ./cli
  web:
    taskfile: ./web/Taskfile.yaml
    dir: ./web
  infra:
    taskfile: ./infra/Taskfile.yaml
    dir: ./infra

tasks:
  sync-api:
    desc: Sync OpenAPI and regenerate web API client
    cmds:
      - task: api:openapi
      - task: web:gen-api

  all:fix:
    desc: Run fix tasks for all modules
    deps: [api:fix, cli:fix, web:fix, infra:aws:fix]

  all:ci:
    desc: Run CI checks for all modules
    deps: [api:ci, cli:ci, web:ci, infra:ci]

  all:build:
    desc: Build all modules for production
    deps: [api:build, cli:build, web:build]
  
  deploy:
    desc: Deploy all modules to production
    cmds:
      - task: all:build
      - task: infra:deploy

  dev:
    desc: Run development environment with API and web servers
    deps: [infra:aws:sync-dot-env]
    cmds:
      - task --parallel api:dev web:dev infra:ddb:up
