version: "3"

tasks:
  ddb:up:
    cmds:
      - docker compose up -d

  ddb:down:
    cmds:
      - docker compose down -v

  ddb:create-tables:
    cmds:
      - bash ./infra/scripts/dynamodb/wait.sh
      - bash ./infra/scripts/dynamodb/create-tables.sh

  ddb:init:
    deps:
      - ddb:up
    cmds:
      - task: ddb:create-tables

  api:fmt:
    dir: api
    cmds:
      - uv run ruff format .

  api:lint:
    dir: api
    cmds:
      - uv run ruff check . --fix

  api:fix:
    dir: api
    deps: [api:fmt, api:lint]

  api:ci:
    deps: [api:fix]
    cmds:
      - git diff --exit-code

  api:dev:
    dir: api
    cmds:
      - uv run uvicorn app.main:app --reload --reload-dir app

  cli:fmt:
    dir: cli
    cmds:
      - go fmt ./...
      - git diff --exit-code

  cli:vet:
    dir: cli
    cmds:
      - go vet ./...

  cli:fix:
    dir: cli
    deps: [cli:fmt, cli:vet]

  cli:test:
    dir: cli
    cmds:
      - go test ./...

  cli:build:
    dir: cli
    cmds:
      - go build .

  cli:ci:
    deps: [cli:fix, cli:test, cli:build]
    cmds:
      - git diff --exit-code

  web:fmt:
    dir: web
    cmds:
      - pnpm fmt

  web:lint:
    dir: web
    cmds:
      - pnpm lint

  web:fix:
    dir: web
    cmds:
      - pnpm fix

  web:build:
    dir: web
    cmds:
      - pnpm build

  web:ci:
    deps: [web:fix, web:build]
    cmds:
      - git diff --exit-code

  infra:fmt:
    dir: infra/terraform
    cmds:
      - terraform fmt -recursive