version: "3"

tasks:
  ddb:up:
    cmds:
      - docker compose up -d

  ddb:down:
    cmds:
      - docker compose down -v

  ddb:create-tables:
    cmds:
      - bash ./infra/scripts/dynamodb/wait.sh
      - bash ./infra/scripts/dynamodb/create-tables.sh

  ddb:init:
    deps:
      - ddb:up
    cmds:
      - task: ddb:create-tables

  api:fmt:
    dir: api
    cmds:
      - uv run ruff format .

  api:lint:
    dir: api
    cmds:
      - uv run ruff check . --fix
      - uv run ty check .

  api:fix:
    dir: api
    deps: [api:fmt, api:lint]

  api:ci:
    cmds:
      - task: api:fix
      - git diff --exit-code -- api

  api:dev:
    dir: api
    cmds:
      - uv run uvicorn app.main:app --reload --reload-dir app

  cli:fmt:
    dir: cli
    cmds:
      - go fmt ./...

  cli:vet:
    dir: cli
    cmds:
      - go vet ./...

  cli:fix:
    dir: cli
    deps: [cli:fmt, cli:vet]

  cli:test:
    dir: cli
    cmds:
      - go test ./...

  cli:build:
    dir: cli
    cmds:
      - go build .

  cli:ci:
    cmds:
      - task: cli:fix
      - task: cli:test
      - task: cli:build
      - git diff --exit-code -- cli

  web:fmt:
    dir: web
    cmds:
      - pnpm fmt

  web:lint:
    dir: web
    cmds:
      - pnpm lint

  web:fix:
    dir: web
    cmds:
      - pnpm fix

  web:build:
    dir: web
    cmds:
      - pnpm build

  web:ci:
    cmds:
      - task: web:fix
      - task: web:build
      - git diff --exit-code -- web

  infra:init:
    dir: infra/terraform
    cmds:
      - terraform init

  infra:fmt:
    dir: infra/terraform
    cmds:
      - terraform fmt -recursive

  infra:validate:
    dir: infra/terraform
    cmds:
      - terraform validate
  
  infra:fix:
    dir: infra/terraform
    deps: [infra:init]
    cmds:
      - task: infra:fmt
      - task: infra:validate
  
  infra:plan:
      dir: infra/terraform
      deps: [infra:fix]
      cmds:
        - terraform plan

  infra:apply:
    dir: infra/terraform
    deps: [infra:fix]
    cmds:
      - terraform apply -auto-approve
  
  infra:destroy:
    dir: infra/terraform
    deps: [infra:fix]
    cmds:
      - terraform destroy -auto-approve

  infra:ci:
    dir: infra/terraform
    cmds:
      - task: infra:fix
      - git diff --exit-code -- infra/terraform
  
  all:ci:
    deps: [api:ci, cli:ci, web:ci, infra:ci]

  all:fix:
    deps: [api:fix, cli:fix, web:fix, infra:fix]