version: "3"

includes:
  local:
    taskfile: ./envs/local/Taskfile.yaml
    dir: ./envs/local
  prod:
    taskfile: ./envs/prod/Taskfile.yaml
    dir: ./envs/prod

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  ci:
    desc: Run infra checks for staged stacks
    cmds:
      - task: prod:fix
      - git diff --exit-code -- .
