import type { DashboardViewModel } from "@/features/dashboard/types";

export type DashboardWorkspaceManagementProps = {
  workspaceDraftName: string;
  transferOwnerUserId: string;
  transferOwnerOptions: Array<{ id: string; name: string }>;
  editingWorkspaceId: string | null;
  transferWorkspaceId: string | null;
  pendingDeleteWorkspaceId: string | null;
  pendingRevokeInvitationId: string | null;
  invitations: DashboardViewModel["invitations"];
  isWorkspaceSubmitting: boolean;
  isWorkspacesLoading: boolean;
  isWorkspacesError: boolean;
  isInvitationsLoading: boolean;
  isInvitationsError: boolean;
  isInvitationsForbidden: boolean;
  isWorkspaceFormOpen: boolean;
  isWorkspaceTransferDialogOpen: boolean;
  onOpenWorkspaceCreateForm: () => void;
  onStartEditWorkspace: (workspaceId: string) => void;
  onWorkspaceDraftNameChange: (value: string) => void;
  onCloseWorkspaceForm: () => void;
  onSubmitWorkspace: () => void;
  onOpenWorkspaceTransferDialog: (workspaceId: string) => void;
  onTransferOwnerUserIdChange: (value: string) => void;
  onCloseWorkspaceTransferDialog: () => void;
  onSubmitWorkspaceTransfer: () => void;
  onRequestRevokeInvitation: (invitationId: string) => void;
  onCancelRevokeInvitation: () => void;
  onConfirmRevokeInvitation: () => void;
  onRequestDeleteWorkspace: (workspaceId: string) => void;
  onCancelDeleteWorkspace: () => void;
  onConfirmDeleteWorkspace: () => void;
  canCreateWorkspace: boolean;
  canManageWorkspace: boolean;
};

export type DashboardPageViewProps = {
  model: DashboardViewModel;
  workspaceManagement: DashboardWorkspaceManagementProps;
  canManageHosts: boolean;
  canManageMembers: boolean;
  canManageJobs: boolean;
  jobsUiState: "ready" | "loading" | "empty" | "error";
  isRefreshing: boolean;
  onLocaleChange: (locale: string) => void;
  onWorkspaceChange: (workspaceId: string) => void;
  onHostChange: (hostId: string) => void;
  onQueryChange: (query: string) => void;
  onRefresh: () => void;
  onApplyFilters: () => void;
  onSignOut: () => void;
  isUserProfileDialogOpen: boolean;
  userProfileDraftName: string;
  isUserProfileSubmitting: boolean;
  onOpenUserProfileDialog: () => void;
  onCloseUserProfileDialog: () => void;
  onUserProfileDraftNameChange: (value: string) => void;
  onSubmitUserProfile: () => void;
  selectedJobId: string | null;
  onSelectJob: (jobId: string) => void;
  pendingDeleteJobId: string | null;
  isJobSubmitting: boolean;
  onRequestDeleteJob: (jobId: string) => void;
  onCancelDeleteJob: () => void;
  onConfirmDeleteJob: () => void;
  onSelectPreviousJob: (jobId: string) => void;
  onSelectNextJob: (jobId: string) => void;
  hostDraftName: string;
  editingHostId: string | null;
  hostToken: string | null;
  hostTokenMessage: string | null;
  isHostSubmitting: boolean;
  isHostsLoading: boolean;
  isHostsError: boolean;
  isHostFormOpen: boolean;
  pendingDeleteHostId: string | null;
  onOpenHostCreate: () => void;
  onHostDraftChange: (value: string) => void;
  onHostSubmit: () => void;
  onHostCopyToken: () => void;
  onHostStartEdit: (hostId: string) => void;
  onHostCloseForm: () => void;
  onHostRequestDelete: (hostId: string) => void;
  onHostCancelDelete: () => void;
  onHostConfirmDelete: () => void;
  memberDraftUserId: string;
  memberDraftRole: string;
  memberInviteRole: string;
  memberEditingUserId: string | null;
  memberEditingRole: string;
  memberInvitationUrl: string | null;
  pendingDeleteMemberUserId: string | null;
  isMemberSubmitting: boolean;
  isMembersLoading: boolean;
  isMembersError: boolean;
  isMemberAddDialogOpen: boolean;
  isMemberInviteDialogOpen: boolean;
  isMemberRoleDialogOpen: boolean;
  onOpenMemberAddDialog: () => void;
  onCloseMemberAddDialog: () => void;
  onOpenMemberInviteDialog: () => void;
  onCloseMemberInviteDialog: () => void;
  onMemberDraftUserIdChange: (value: string) => void;
  onMemberDraftRoleChange: (value: string) => void;
  onMemberInviteRoleChange: (value: string) => void;
  onMemberEditingRoleChange: (value: string) => void;
  onMemberSubmitAdd: () => void;
  onMemberGenerateInvite: () => void;
  onMemberCopyInviteLink: () => void;
  onMemberRequestEdit: (userId: string, role: string) => void;
  onMemberCloseEditDialog: () => void;
  onMemberSubmitRoleUpdate: () => void;
  onMemberRequestDelete: (userId: string) => void;
  onMemberCancelDelete: () => void;
  onMemberConfirmDelete: () => void;
};
