version: "3"

tasks:
  init:
    desc: Initialize Cloudflare Terraform
    cmds:
      - terraform init

  fmt:
    desc: Format Cloudflare Terraform files
    cmds:
      - terraform fmt -recursive

  validate:
    desc: Validate Cloudflare Terraform config
    cmds:
      - terraform validate

  fix:
    desc: Run Cloudflare Terraform init, fmt, and validate
    cmds:
      - task: init
      - task: fmt
      - task: validate

  sync-from-aws:
    desc: Sync Cloudflare auto tfvars from AWS Terraform outputs
    cmds:
      - bash ../../scripts/cloudflare/sync-from-aws.sh

  plan:
    desc: Generate Cloudflare Terraform plan
    deps: [fix, sync-from-aws]
    cmds:
      - terraform plan

  apply:
    desc: Apply Cloudflare Terraform changes
    deps: [fix, sync-from-aws]
    cmds:
      - terraform apply -auto-approve

  destroy:
    desc: Destroy Cloudflare Terraform resources
    deps: [fix]
    cmds:
      - terraform destroy -auto-approve
