#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
AWS_TF_DIR="$ROOT_DIR/infra/terraform/aws"
CF_AUTO_TFVARS_FILE="$ROOT_DIR/infra/terraform/cloudflare/from_aws.auto.tfvars"

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required for infra/scripts/cloudflare/sync-from-aws.sh" >&2
  exit 1
fi

outputs_json="$(terraform -chdir="$AWS_TF_DIR" output -json)"
api_invoke_url="$(echo "$outputs_json" | jq -r '.api_invoke_url.value // empty')"

if [[ -z "$api_invoke_url" ]]; then
  echo "api_invoke_url was not found in AWS Terraform outputs." >&2
  echo "Run: task infra:aws:apply" >&2
  exit 1
fi

cat > "$CF_AUTO_TFVARS_FILE" <<EOF
# Auto-generated by infra/scripts/cloudflare/sync-from-aws.sh
# Do not edit manually.
api_origin = "${api_invoke_url%/}"
EOF

echo "Synced Cloudflare auto tfvars from AWS outputs:"
echo "- $CF_AUTO_TFVARS_FILE"
