import type { DashboardViewModel, JobListItem } from "@/features/dashboard/types";
import type { Locale, MessageKey } from "@/i18n/messages";

type UseDashboardViewModelParams = {
  locale: Locale;
  t: (key: MessageKey) => string;
  updatedAt: string;
  workspaceId: string;
  hostId: string;
  query: string;
  workspaces: DashboardViewModel["filters"]["workspaceOptions"];
  currentUser: DashboardViewModel["currentUser"];
  hostOptions: DashboardViewModel["filters"]["hostOptions"];
  hosts: DashboardViewModel["hosts"];
  members: DashboardViewModel["members"];
  invitations: DashboardViewModel["invitations"];
  jobs: JobListItem[];
  selectedJob: DashboardViewModel["selectedJob"];
};

export const buildDashboardViewModel = ({
  locale,
  t,
  updatedAt,
  workspaceId,
  hostId,
  query,
  workspaces,
  currentUser,
  hostOptions,
  hosts,
  members,
  invitations,
  jobs,
  selectedJob,
}: UseDashboardViewModelParams): DashboardViewModel => {
  return {
    title: t("dashboard_title"),
    subtitle: t("dashboard_subtitle"),
    texts: {
      missionControl: t("dashboard_mission_control"),
      currentUser: t("dashboard_current_user"),
      profileEdit: t("dashboard_profile_edit"),
      profileName: t("dashboard_profile_name"),
      profileUpdated: t("dashboard_profile_updated"),
      profileUpdateError: t("dashboard_profile_update_error"),
      updatedAt: t("dashboard_updated_at_label"),
      refresh: t("dashboard_refresh"),
      signOut: t("dashboard_sign_out"),
      filters: t("dashboard_filters"),
      apply: t("dashboard_apply"),
      recentJobs: t("dashboard_recent_jobs"),
      noJobs: t("dashboard_empty_jobs"),
      jobsError: t("dashboard_jobs_error"),
      jobDeleted: t("dashboard_job_deleted"),
      jobCrudError: t("dashboard_job_crud_error"),
      jobDeleteConfirmTitle: t("dashboard_job_delete_confirm_title"),
      jobDeleteConfirmDescription: t("dashboard_job_delete_confirm_description"),
      detail: t("dashboard_detail"),
      selectedJob: t("dashboard_selected_job"),
      jobId: t("dashboard_job_id"),
      project: t("dashboard_project"),
      latestLogs: t("dashboard_latest_logs"),
      command: t("dashboard_command"),
      args: t("dashboard_args"),
      tags: t("dashboard_tags"),
      status: t("dashboard_status"),
      startedAt: t("dashboard_started_at"),
      finishedAt: t("dashboard_finished_at"),
      duration: t("dashboard_duration"),
      error: t("dashboard_error"),
      viewFull: t("dashboard_view_full"),
      detailEmpty: t("dashboard_detail_empty"),
      logsEmpty: t("dashboard_logs_empty"),
      workspaces: t("dashboard_workspaces"),
      workspaceName: t("dashboard_workspace_name"),
      workspaceNewOwnerUserId: t("dashboard_workspace_new_owner_user_id"),
      workspaceTransferOwner: t("dashboard_workspace_transfer_owner"),
      invitations: t("dashboard_invitations"),
      invitationRole: t("dashboard_invitation_role"),
      invitationCreatedBy: t("dashboard_invitation_created_by"),
      invitationExpiresAt: t("dashboard_invitation_expires_at"),
      invitationUsedAt: t("dashboard_invitation_used_at"),
      invitationStatusActive: t("dashboard_invitation_status_active"),
      invitationStatusUsed: t("dashboard_invitation_status_used"),
      invitationStatusExpired: t("dashboard_invitation_status_expired"),
      invitationRevokeConfirmTitle: t("dashboard_invitation_revoke_confirm_title"),
      invitationRevokeConfirmDescription: t("dashboard_invitation_revoke_confirm_description"),
      invitationsEmpty: t("dashboard_invitations_empty"),
      invitationsError: t("dashboard_invitations_error"),
      invitationRevoked: t("dashboard_invitation_revoked"),
      invitationCrudError: t("dashboard_invitation_crud_error"),
      workspacesEmpty: t("dashboard_workspaces_empty"),
      workspacesError: t("dashboard_workspaces_error"),
      workspaceCreated: t("dashboard_workspace_created"),
      workspaceUpdated: t("dashboard_workspace_updated"),
      workspaceDeleted: t("dashboard_workspace_deleted"),
      workspaceOwnerTransferred: t("dashboard_workspace_owner_transferred"),
      workspaceCrudError: t("dashboard_workspace_crud_error"),
      workspaceDeleteConfirmTitle: t("dashboard_workspace_delete_confirm_title"),
      workspaceDeleteConfirmDescription: t("dashboard_workspace_delete_confirm_description"),
      currentWorkspace: t("dashboard_current_workspace"),
      workspaceScopeHint: t("dashboard_workspace_scope_hint"),
      tabOverview: t("dashboard_tab_dashboard"),
      tabMembers: t("dashboard_tab_members"),
      hosts: t("dashboard_hosts"),
      hostName: t("dashboard_host_name"),
      members: t("dashboard_members"),
      memberUserId: t("dashboard_member_user_id"),
      memberUsername: t("dashboard_member_username"),
      memberRole: t("dashboard_member_role"),
      membersEmpty: t("dashboard_members_empty"),
      membersError: t("dashboard_members_error"),
      memberAdded: t("dashboard_member_added"),
      memberUpdated: t("dashboard_member_updated"),
      memberRemoved: t("dashboard_member_removed"),
      memberCrudError: t("dashboard_member_crud_error"),
      invitationLink: t("dashboard_invitation_link"),
      invitationLinkPlaceholder: t("dashboard_invitation_link_placeholder"),
      generateInvite: t("dashboard_generate_invite"),
      copyLink: t("dashboard_copy_link"),
      copyToken: t("dashboard_copy_token"),
      invitationLinkCreated: t("dashboard_invitation_link_created"),
      invitationLinkCopied: t("dashboard_invitation_link_copied"),
      invitationLinkCreateError: t("dashboard_invitation_link_create_error"),
      add: t("dashboard_add"),
      edit: t("dashboard_edit"),
      update: t("dashboard_update"),
      cancel: t("dashboard_cancel"),
      delete: t("dashboard_delete"),
      hostsEmpty: t("dashboard_hosts_empty"),
      hostsError: t("dashboard_hosts_error"),
      hostToken: t("dashboard_host_token"),
      hostTokenCopied: t("dashboard_host_token_copied"),
      hostTokenCopyError: t("dashboard_host_token_copy_error"),
      hostCrudError: t("dashboard_host_crud_error"),
      hostCreated: t("dashboard_host_created"),
      hostUpdated: t("dashboard_host_updated"),
      hostDeleted: t("dashboard_host_deleted"),
      hostDeleteConfirmTitle: t("dashboard_host_delete_confirm_title"),
      hostDeleteConfirmDescription: t("dashboard_host_delete_confirm_description"),
      memberDeleteConfirmTitle: t("dashboard_member_delete_confirm_title"),
      memberDeleteConfirmDescription: t("dashboard_member_delete_confirm_description"),
      noPermission: t("dashboard_no_permission"),
      snapshotTracked: t("dashboard_snapshot_tracked"),
      snapshotRunning: t("dashboard_snapshot_running"),
      snapshotCompleted: t("dashboard_snapshot_completed"),
      snapshotFailed: t("dashboard_snapshot_failed"),
      statusLabels: {
        running: t("status_running"),
        completed: t("status_completed"),
        failed: t("status_failed"),
        canceled: t("status_canceled"),
      },
    },
    language: {
      label: t("dashboard_language"),
      current: locale,
      options: [
        { id: "en", name: t("locale_en") },
        { id: "ja", name: t("locale_ja") },
      ],
    },
    filters: {
      workspaceLabel: t("dashboard_filter_workspace"),
      hostLabel: t("dashboard_filter_host"),
      queryLabel: t("dashboard_filter_query"),
      workspaceOptions: workspaces,
      hostOptions,
      workspaceId,
      hostId,
      query,
    },
    snapshot: {
      total: jobs.length,
      running: jobs.filter((job) => job.status === "running").length,
      completed: jobs.filter((job) => job.status === "completed").length,
      failed: jobs.filter((job) => job.status === "failed").length,
      updatedAt,
    },
    hosts,
    members,
    invitations,
    currentUser,
    jobs,
    selectedJob,
  };
};
