import type { DashboardSelectOption } from "@/features/dashboard/types";

export type DashboardWorkspacesSectionProps = {
  title: string;
  workspaceNameLabel: string;
  activeWorkspaceId: string;
  newOwnerUserIdLabel: string;
  transferOwnerLabel: string;
  addLabel: string;
  editLabel: string;
  updateLabel: string;
  cancelLabel: string;
  deleteLabel: string;
  emptyLabel: string;
  errorLabel: string;
  deleteConfirmTitle: string;
  deleteConfirmDescription: string;
  noPermissionLabel: string;
  canCreate: boolean;
  canManage: boolean;
  workspaces: DashboardSelectOption[];
  workspaceDraftName: string;
  transferOwnerUserId: string;
  transferOwnerOptions: DashboardSelectOption[];
  editingWorkspaceId: string | null;
  transferWorkspaceId: string | null;
  pendingDeleteWorkspaceId: string | null;
  isLoading: boolean;
  isError: boolean;
  isSubmitting: boolean;
  isFormOpen: boolean;
  isTransferDialogOpen: boolean;
  onSelectWorkspace: (workspaceId: string) => void;
  onOpenCreate: () => void;
  onStartEdit: (workspaceId: string) => void;
  onDraftNameChange: (value: string) => void;
  onCloseForm: () => void;
  onSubmitWorkspace: () => void;
  onOpenTransfer: (workspaceId: string) => void;
  onTransferOwnerUserIdChange: (value: string) => void;
  onCloseTransfer: () => void;
  onSubmitTransfer: () => void;
  onRequestDelete: (workspaceId: string) => void;
  onCancelDelete: () => void;
  onConfirmDelete: () => void;
};
