import type { DashboardInvitationItem, DashboardSelectOption } from "@/features/dashboard/types";

export type DashboardWorkspacesSectionProps = {
  title: string;
  workspaceNameLabel: string;
  activeWorkspaceName: string;
  newOwnerUserIdLabel: string;
  transferOwnerLabel: string;
  invitationsTitle: string;
  invitationRoleLabel: string;
  invitationCreatedByLabel: string;
  invitationExpiresAtLabel: string;
  invitationUsedAtLabel: string;
  invitationStatusActiveLabel: string;
  invitationStatusUsedLabel: string;
  invitationStatusExpiredLabel: string;
  invitationRevokeConfirmTitle: string;
  invitationRevokeConfirmDescription: string;
  revokeLabel: string;
  invitationsEmptyLabel: string;
  invitationsErrorLabel: string;
  addLabel: string;
  updateLabel: string;
  cancelLabel: string;
  deleteLabel: string;
  emptyLabel: string;
  errorLabel: string;
  deleteConfirmTitle: string;
  deleteConfirmDescription: string;
  noPermissionLabel: string;
  canCreate: boolean;
  canManage: boolean;
  workspaces: DashboardSelectOption[];
  invitations: DashboardInvitationItem[];
  workspaceDraftName: string;
  transferOwnerUserId: string;
  transferOwnerOptions: DashboardSelectOption[];
  editingWorkspaceId: string | null;
  transferWorkspaceId: string | null;
  pendingDeleteWorkspaceId: string | null;
  pendingRevokeInvitationId: string | null;
  isLoading: boolean;
  isError: boolean;
  isInvitationsLoading: boolean;
  isInvitationsError: boolean;
  isSubmitting: boolean;
  isFormOpen: boolean;
  isTransferDialogOpen: boolean;
  onOpenCreate: () => void;
  onStartEdit: (workspaceId: string) => void;
  onDraftNameChange: (value: string) => void;
  onCloseForm: () => void;
  onSubmitWorkspace: () => void;
  onOpenTransfer: (workspaceId: string) => void;
  onTransferOwnerUserIdChange: (value: string) => void;
  onCloseTransfer: () => void;
  onSubmitTransfer: () => void;
  onRequestRevokeInvitation: (invitationId: string) => void;
  onCancelRevokeInvitation: () => void;
  onConfirmRevokeInvitation: () => void;
  onRequestDelete: (workspaceId: string) => void;
  onCancelDelete: () => void;
  onConfirmDelete: () => void;
};
